### ISSUE TITLE
Library not loaded: /usr/local/lib/libopenblas_haswellp-r0.2.19.dylib

### ISSUE THREAD

**Issue by maokk** [TomHeaven/pytorch-osx-build#17]
thanks for your great job, I use your Pytorch1.4 build before, for now I want update to 1.7 with cuda10.1.243 and cudnn7.6.5

after finish and copy magma file to /usr/local/lib
in python I want import torch get error below, pls help thank you~~

(pytorch_1.0) maokkdeMac-Pro:local maokk_mp$ python
Python 3.7.5 (default, Oct 25 2019, 10:52:18) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maokk_mp/anaconda3/envs/pytorch_1.0/lib/python3.7/site-packages/torch/__init__.py", line 190, in <module>
    from torch._C import *
ImportError: dlopen(/Users/maokk_mp/anaconda3/envs/pytorch_1.0/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/lib/libopenblas_haswellp-r0.2.19.dylib
  Referenced from: /usr/local/lib/libmagma.dylib
  Reason: image not found
>>>

**Comment by maokk** [comment]
my mistake I should copy 5 files into /usr/local/lib
after do this 

>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maokk_mp/anaconda3/envs/pytorch_1.0/lib/python3.7/site-packages/torch/__init__.py", line 190, in <module>
    from torch._C import *
ImportError: dlopen(/Users/maokk_mp/anaconda3/envs/pytorch_1.0/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 2): Symbol not found: ___addtf3
  Referenced from: /usr/local/lib/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/libquadmath.0.dylib

**Comment by TomHeaven** [comment]
libSystem.B.dylib seems to be a system dynamic library of macOS. 

What exact version of macOS are you using? You can find the exact version in the top-left menu bar by Apple->About->Software.

**Comment by maokk** [comment]
thanks for your reply, I find libquadmath.0.dylib in my filesystem and replace. it works
now the Pytorch works perfect in my old Mac Pro 10.13.6 with titanXP
thanks again for your great job

**Comment by TomHeaven** [comment]
Glad to hear that.

**Comment by jjjjohnson** [comment]
I have the same problem and have not solved it...
ImportError: dlopen(/Volumes/D/opt/anaconda3/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 2): Symbol not found: ___addtf3
  Referenced from: /usr/local/lib/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/libquadmath.0.dylib

**Comment by TomHeaven** [comment]
> I have the same problem and have not solved it...
> ImportError: dlopen(/Volumes/D/opt/anaconda3/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 2): Symbol not found: ___addtf3
> Referenced from: /usr/local/lib/libquadmath.0.dylib
> Expected in: /usr/lib/libSystem.B.dylib
> in /usr/local/lib/libquadmath.0.dylib

Download libquadmath.0.dylib from usr_local_lib folder of the master branch, and replace the file in your /usr/local/lib/ path.

**Comment by alvis** [comment]
I just encountered the same issue. My system is also 10.13, but checking `libSystem.B.dylib` with `nm` indeed shows that there's no `___addtf3` in the library. It's strange because `libSystem.B.dylib` comes from the MacOS distribution. A possible reason is that `libSystem.B.dylib` wasn't get updated when I upgraded my system from 10.11 -> 10.12 -> 10.13. I don't know. Just curious, @TomHeaven  does `___addtf3` present in your `libSystem.B.dylib`? What's the file size & checksum?

Anyhow, I configured out a way to solve the issue. Instead of using the supplied lib in the master branch, I soft linked `libquadmath.0.dylib` (also `libgfortran.3.dylib`) with the one supplied by gcc@6 (eg `ln -s /usr/local/lib/gcc/6/libgfortran.3.dylib /usr/local/libgfortran.3.dylib`), and it works. Note. you need gcc@6 as it's the last version providing the needed `libgfortran.3.dylib`. the latest gcc@10 doesn't work.

**Comment by TomHeaven** [comment]
MacOS 10.13 is an aged system now. I keep using it for years and some dependencies may become deprecated. The workaround is to place those deprecated libraries in your system.
