### ISSUE TITLE
Provide conda package.

### ISSUE THREAD

**Issue by javagg** [TomHeaven/pytorch-osx-build#5]
That would be great if the conda packages can be provided since more and more users are using anaconda to manage their python development environments.

**Comment by TomHeaven** [comment]
Providing conda package is not in my schedule at present. I'm not using Anaconda in Mac OS since the operating system is born with Python 2.7 and Homebrew brings Python 3.

Moreover, pip can work with Conda in my mind. You can check this link:
https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment
